"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


limit = 4000000

fib = [1,2]
even_fib_sum = 0
while max(fib) < limit:
    new_fib = fib[-1] + fib[-2]
    fib.append(new_fib)
    continue

for number in fib:
    if number % 2 ==0:
        even_fib_sum += number

print("The sum of the even terms of the Fibonacci sequence under 4,000,000 is ",even_fib_sum)

